### ISSUE TITLE
Create flashing animation when clicking to change mode

### ISSUE THREAD

**Issue by QuocZuong** [QuocZuong/monkeytype#3]
When clicking on each button it will have a flashing animation. Go to monkeytype.com for more details.
![image](https://github.com/QuocZuong/monkeytype/assets/110612155/dc1b8cc0-e3cb-4e72-91f8-766902c325b7)

**Comment by PhenChua29** [comment]
Done!

**Comment by PhenChua29** [comment]
Just figured out that I did it the wrong way, may work on it again
