### ISSUE TITLE
Typing field shouldn't allow the Grammarly icon to pop up in the DOM

### ISSUE THREAD

**Issue by PhenChua29** [QuocZuong/monkeytype#4]
![image](https://github.com/QuocZuong/monkeytype/assets/89496400/8be91400-4c7e-4cc1-af9d-55276d410522)

Typing field shouldn't allow the Grammarly icon to pop up in the DOM. It makes the overall typing div padded into the left.

**Comment by QuocZuong** [comment]
I already fixed it without replacing textarea to div and also prevented some user behaviors like ctrl + a or select text.  Please help me test it on Windows if it works as expected. Goodbye Grammarly

**Comment by PhenChua29** [comment]
It works perfectly fine on Windows. However, you somehow also disable the ability to use other key combinations related to the "Ctrl" button.

E,g, the "Ctrl + tab", "Ctrl + number", "Ctrl + d", etc. 

See #14 for more information.
